# Generated by Django 6.0.5 on 2026-05-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_category_options_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="playlists", to="content.track"
            ),
        ),
    ]
