# Generated by Django 6.0.5 on 2026-05-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_playlist_tracks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playlists",
                to="content.category",
            ),
        ),
    ]
