# Generated by Django 6.0.5 on 2026-05-27 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_alter_playlist_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playlist",
            name="unique_playlist_name_author",
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("name", "author", "type", "is_official"),
                name="unique_playlist_name_author",
            ),
        ),
    ]
