# Generated by Django 6.0.5 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_remove_playlist_unique_playlist_name_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
