# Generated by Django 6.0.5 on 2026-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_alter_track_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tracks/images/"),
        ),
    ]
