# Generated by Django 6.0.5 on 2026-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_alter_track_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("processing", "В обработке"),
                    ("pending", "На проверке"),
                    ("rejected", "Отклонено"),
                    ("published", "Опубликовано"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
