# Generated by Django 6.0.5 on 2026-06-03 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_alter_artist_avatar"),
        ("content", "0011_alter_track_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="albums/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="playlist",
            name="unique_playlist_name_author",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На проверке"),
                    ("rejected", "Отклонено"),
                    ("approved", "Одобрено"),
                    ("published", "Опубликовано"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("processing", "В обработке"),
                    ("pending", "На проверке"),
                    ("rejected", "Отклонено"),
                    ("approved", "Одобрено"),
                    ("published", "Опубликовано"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("name", "author", "type", "is_official"),
                name="unique_playlist_name_author_type_is_official",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albums",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="albums",
                to="content.category",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracks",
                to="content.album",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                fields=("name", "author"), name="unique_album_name_author"
            ),
        ),
    ]
