# Generated by Django 6.0.5 on 2026-06-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_album_remove_playlist_unique_playlist_name_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracks",
                to="content.album",
            ),
        ),
    ]
