# Generated by Django 6.0.5 on 2026-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_album_rejection_message_album_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("processing", "В обработке"),
                    ("pending", "На проверке"),
                    ("rejected", "Отклонено"),
                    ("approved", "Одобрено"),
                    ("published", "Опубликовано"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
