# Generated by Django 6.0.5 on 2026-06-08 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_playlist_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="content.track"
                    ),
                ),
            ],
        ),
    ]
