# Generated by Django 6.0.5 on 2026-06-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_tracktext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracktext",
            name="track",
        ),
        migrations.AddField(
            model_name="track",
            name="text",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.tracktext",
            ),
        ),
    ]
