# Generated by Django 6.0.5 on 2026-06-10 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_remove_tracktext_track_track_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
    ]
