# Generated by Django 6.0.5 on 2026-07-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_remove_artist_user_artistprofile"),
        ("content", "0022_favoritealbum_favoriteartist_favoritetrack"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favoritealbum",
            name="unique_user_favorite_album",
        ),
        migrations.RemoveConstraint(
            model_name="favoriteartist",
            name="unique_user_favorite_artist",
        ),
        migrations.RemoveConstraint(
            model_name="favoritetrack",
            name="unique_user_favorite_track",
        ),
        migrations.RemoveConstraint(
            model_name="playlist",
            name="unique_official_playlist_name_author",
        ),
        migrations.AlterField(
            model_name="album",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albums",
                to="artists.artistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="artists.artistprofile",
            ),
        ),
        migrations.RemoveField(
            model_name="favoriteartist",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="favoriteartist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="favoritetrack",
            name="track",
        ),
        migrations.RemoveField(
            model_name="favoritetrack",
            name="user",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="author",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="category",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="tracks",
        ),
        migrations.DeleteModel(
            name="FavoriteAlbum",
        ),
        migrations.DeleteModel(
            name="FavoriteArtist",
        ),
        migrations.DeleteModel(
            name="FavoriteTrack",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
