import collection1 from '../assets/img/collections/1.svg';
import collection2 from '../assets/img/collections/2.svg';
import collection3 from '../assets/img/collections/3.svg';
import collection4 from '../assets/img/collections/4.svg';
import popImg from '../assets/img/genres/popImg.png';
import metalImg from '../assets/img/genres/metalImg.png';
import indieImg from '../assets/img/genres/indieImg.png';
import alternativeImg from '../assets/img/genres/alternativeImg.png';
import rockImg from '../assets/img/genres/rockImg.png';
import searchImg from '../assets/img/search.svg';
import userImg from '../assets/img/user.svg';
import sunImg from '../assets/img/sun.svg';
import logoImg from '../assets/img/logo.svg';
import menuImg from '../assets/img/menu.svg';
import closeImg from '../assets/img/menu-close.svg';
import homeImg from '../assets/img/home.svg';
import favoriteImg from '../assets/img/favorite.svg';
import plusImg from '../assets/img/plus.svg';
import playlistImg from '../assets/img/playlist.svg';
import playImg from '../assets/img/play.svg';
import arrowImg from '../assets/img/arrow.svg';
import soundImg from '../assets/img/sound-img.svg';
import playImg18 from '../assets/img/play-18.svg';
import pauseImg18 from '../assets/img/pause-18.svg';
import arrow2Img from '../assets/img/arrow2.svg';
import pauseImg from '../assets/img/pause.svg';
import volumeImg from '../assets/img/volume.svg';
import volumeMuteImg from '../assets/img/volume.svg';

export const coll1: string = String(collection1);
export const coll2: string = String(collection2);
export const coll3: string = String(collection3);
export const coll4: string = String(collection4);
export const pop: string = String(popImg);
export const metal: string = String(metalImg);
export const indie: string = String(indieImg);
export const alternative: string = String(alternativeImg);
export const rock: string = String(rockImg);
export const search: string = String(searchImg);
export const user: string = String(userImg);
export const sun: string = String(sunImg);
export const logo: string = String(logoImg);
export const menu: string = String(menuImg);
export const close: string = String(closeImg);
export const home: string = String(homeImg);
export const favorite: string = String(favoriteImg);
export const plus: string = String(plusImg);
export const playlist: string = String(playlistImg);
export const play: string = String(playImg);
export const arrow: string = String(arrowImg);
export const sound: string = String(soundImg);
export const play18: string = String(playImg18);
export const pause18: string = String(pauseImg18);
export const arrow2: string = String(arrow2Img);
export const pause: string = String(pauseImg);
export const _volumeImg: string = String(volumeImg);
export const volume_mute: string = String(volumeMuteImg);
