import collection1 from '../../public/collections/1.svg';
import collection2 from '../../public/collections/2.svg';
import collection3 from '../../public/collections/3.svg';
import collection4 from '../../public/collections/4.svg';
import logoImg from '../assets/img/logo.svg';
import homeImg from '../assets/img/home.svg';
import favoriteImg from '../assets/img/favorite.svg';
import plusImg from '../assets/img/plus.svg';
import playlistImg from '../assets/img/playlist.svg';
import arrowImg from '../assets/img/arrow.svg';
import volumeImg from '../assets/img/volume.svg';
import volumeMuteImg from '../assets/img/volume-mute.svg';
import favorite1Img from '../assets/img/favorite-1.svg';

export const coll1: string = String(collection1);
export const coll2: string = String(collection2);
export const coll3: string = String(collection3);
export const coll4: string = String(collection4);
export const logo: string = String(logoImg);
export const home: string = String(homeImg);
export const favorite0: string = String(favoriteImg);
export const plus: string = String(plusImg);
export const playlist: string = String(playlistImg);
export const arrow: string = String(arrowImg);
export const _volumeImg: string = String(volumeImg);
export const volume_mute: string = String(volumeMuteImg);
export const favorite1: string = String(favorite1Img);
