import collection1 from '../assets/img/collections/1.svg';
import collection2 from '../assets/img/collections/2.svg';
import collection3 from '../assets/img/collections/3.svg';
import collection4 from '../assets/img/collections/4.svg';
import popImg from '../../public/genres/pop.png';
import metalImg from '../../public/genres/metal.png';
import indieImg from '../../public/genres/indie.png';
import alternativeImg from '../../public/genres/alternative.png';
import rockImg from '../../public/genres/rock.png';
import searchImg from '../assets/img/search.svg';
import logoImg from '../assets/img/logo.svg';
import menuImg from '../assets/img/menu.svg';
import closeImg from '../assets/img/menu-close.svg';
import homeImg from '../assets/img/home.svg';
import favoriteImg from '../assets/img/favorite.svg';
import plusImg from '../assets/img/plus.svg';
import playlistImg from '../assets/img/playlist.svg';
import arrowImg from '../assets/img/arrow.svg';
import volumeImg from '../assets/img/volume.svg';
import volumeMuteImg from '../assets/img/volume-mute.svg';
import favorite1Img from '../assets/img/favorite-1.svg';

export const coll1: string = String(collection1);
export const coll2: string = String(collection2);
export const coll3: string = String(collection3);
export const coll4: string = String(collection4);
export const pop: string = String(popImg);
export const metal: string = String(metalImg);
export const indie: string = String(indieImg);
export const alternative: string = String(alternativeImg);
export const rock: string = String(rockImg);
export const search: string = String(searchImg);
export const logo: string = String(logoImg);
export const menu: string = String(menuImg);
export const close: string = String(closeImg);
export const home: string = String(homeImg);
export const favorite: string = String(favoriteImg);
export const plus: string = String(plusImg);
export const playlist: string = String(playlistImg);
export const arrow: string = String(arrowImg);
export const _volumeImg: string = String(volumeImg);
export const volume_mute: string = String(volumeMuteImg);
export const favorite1: string = String(favorite1Img);
