# Generated by Django 6.0.5 on 2026-05-24 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playlist",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "Плейлист пользователя"),
                    ("artist", "Плейлист исполнителя"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
