# Generated by Django 6.0.5 on 2026-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_playlist_is_official_playlist_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
