# Generated by Django 6.0.5 on 2026-05-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/'),
        ),
    ]
