# Generated by Django 6.0.5 on 2026-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0013_alter_track_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="rejection_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На проверке"),
                    ("rejected", "Отклонено"),
                    ("approved", "Одобрено"),
                    ("published", "Опубликовано"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
