# Generated by Django 6.0.5 on 2026-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_alter_album_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playlist",
            name="unique_playlist_name_author_type_is_official",
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("name", "is_official"), name="unique_official_playlist_name"
            ),
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="author",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="rejection_message",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="type",
        ),
    ]
