# Generated by Django 6.0.5 on 2026-06-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "music",
            "0016_remove_playlist_unique_playlist_name_author_type_is_official_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
