# Generated by Django 6.0.5 on 2026-06-10 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0020_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playlist",
            name="unique_official_playlist_name",
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("name", "is_official", "author"),
                name="unique_official_playlist_name_author",
            ),
        ),
    ]
