# Generated by Django 6.0.5 on 2026-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/users/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/users/"),
        ),
    ]
