# Generated by Django 6.0.5 on 2026-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_role_remove_user_role_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("artist", "Исполнитель"),
                    ("moderator", "Модератор"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
