# Generated by Django 6.0.5 on 2026-07-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", to="authentication.role"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("listener", "Слушатель"),
                    ("artist", "Исполнитель"),
                    ("moderator", "Модератор"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
