# Generated by Django 6.0.5 on 2026-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/artists/'),
        ),
    ]
