# Generated by Django 6.0.5 on 2026-07-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_remove_artist_user_artistprofile"),
        ("content", "0023_remove_favoritealbum_unique_user_favorite_album_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
